<a href="https://colab.research.google.com/github/ihatestudysomuch/pytorch/blob/main/Pytorch_24%EC%9E%A5_RNN_%EC%82%AC%EC%9A%A9%EB%B2%95(API%2C_%EC%98%88%EC%A0%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch - RNN, GRU, LSTM



1.   Pytorch RNN API는 torch.nn.RNN(input_size, hiddne_size, num_layers, batch_first)로 구성되어있다.
  - input_size는 RNN 입력층으로 들어가는 feature값의 개수
  - hidden_size는 은닉 상태의 개수 즉, RNN layer 출력 개수
  - num_layers는 RNN layer의 쌓여져 있는 개수
  - batch_first는 입력받는 데이터에서 첫 번째 차원을 batch로 간주 할 것인지 여부를 설정



In [2]:
import torch

input_data = torch.Tensor([[[1],[2],[3]]]) # (1,3,1) shape을 가지는 입력데이터

MyRNNModel = torch.nn.RNN(input_size = 1, hidden_size = 3, batch_first = True) # 1개의 feature이므로 input_size = 1, 출력으로 3개의 은닉 상태를 가짐(hidden_size는 사용자 재량 설정)

outputs, last_hs = MyRNNModel(input_data) # outputs는 모든 time_stpes, last_hs는 마지막 time_steps

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)

torch.Size([1, 3, 3]) 

 tensor([[[ 0.3955, -0.2367,  0.5484],
         [ 0.8135, -0.4804,  0.6211],
         [ 0.9525, -0.6794,  0.7478]]], grad_fn=<TransposeBackward1>) 

torch.Size([1, 1, 3]) 

 tensor([[[ 0.9525, -0.6794,  0.7478]]], grad_fn=<StackBackward0>)


In [3]:
import torch

input_data = torch.Tensor([ [ [1], [2], [3] ],
                            [ [4], [5], [6] ] ]) # (2, 3, 1) shape


MyRNNModel = torch.nn.RNN(input_size=1, hidden_size=3,
                          batch_first=True) # feature = 1 .. input_size = 1


outputs, last_hs = MyRNNModel(input_data) # 3 time_steps

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)


torch.Size([2, 3, 3]) 

 tensor([[[-0.1083,  0.6846, -0.4876],
         [-0.3943,  0.8193, -0.6307],
         [-0.3839,  0.8774, -0.6864]],

        [[ 0.2766,  0.9434, -0.6131],
         [-0.1402,  0.9783, -0.7488],
         [-0.0889,  0.9843, -0.7860]]], grad_fn=<TransposeBackward1>) 

torch.Size([1, 2, 3]) 

 tensor([[[-0.3839,  0.8774, -0.6864],
         [-0.0889,  0.9843, -0.7860]]], grad_fn=<StackBackward0>)


In [5]:
import torch

input_data = torch.Tensor([ [ [1, 10], [2, 11], [3, 12] ],
                            [ [4, 13], [5, 14], [6, 15] ],
                            [ [7, 16], [8, 17], [9, 18] ] ]) # (3, 3, 2)


MyRNNModel = torch.nn.RNN(input_size=2, hidden_size=6,
                          batch_first=True)


outputs, last_hs = MyRNNModel(input_data)

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)

torch.Size([3, 3, 6]) 

 tensor([[[-0.9998, -0.9980, -0.9701, -0.1336, -0.9641,  0.9501],
         [-1.0000, -0.9864, -0.9909, -0.7416, -0.9428,  0.9901],
         [-1.0000, -0.9820, -0.9915, -0.8698, -0.9236,  0.9968]],

        [[-1.0000, -0.9984, -0.9890, -0.5458, -0.9562,  0.9983],
         [-1.0000, -0.9857, -0.9960, -0.9195, -0.9192,  0.9997],
         [-1.0000, -0.9840, -0.9966, -0.9536, -0.9017,  0.9999]],

        [[-1.0000, -0.9987, -0.9960, -0.7971, -0.9466,  0.9999],
         [-1.0000, -0.9868, -0.9984, -0.9734, -0.8927,  1.0000],
         [-1.0000, -0.9868, -0.9987, -0.9824, -0.8798,  1.0000]]],
       grad_fn=<TransposeBackward1>) 

torch.Size([1, 3, 6]) 

 tensor([[[-1.0000, -0.9820, -0.9915, -0.8698, -0.9236,  0.9968],
         [-1.0000, -0.9840, -0.9966, -0.9536, -0.9017,  0.9999],
         [-1.0000, -0.9868, -0.9987, -0.9824, -0.8798,  1.0000]]],
       grad_fn=<StackBackward0>)
