<a href="https://colab.research.google.com/github/ihatestudysomuch/pytorch/blob/main/Pytorch_10%EC%9E%A5_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EA%B0%9C%EB%85%90_%EB%B0%8F_%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 인공지능 * 딥러닝 * 머신러닝


1.   인공지능 -> 머신러닝 -> 딥러닝 순의 하위 개념(하위 개념으로 갈 수록 더 정교화)
2.   추상적 -> 예측 -> 강한 예측
  - 머신러닝은 데이터를 이용하여 데이터 특성과 패턴을 학습하고 그 결과를 바탕으로 미지의 데이터에 대한 미래를 예측
  - 딥러닝은 인공 신경망(ANN, Artifical Neural Network)을 이용하는 것이 머신 러닝과의 차이라고 할 수 있다.

1.   앞서 배운 Linear Regression, Logistic Regression은 머신러닝에 더 적합하다.
2.   머신러닝은 입력층 - 출력층으로 통하지만 딥러닝은 입력층 - 은닉층 - 출력층으로 구성되어있다.
  - 예시로 모델 구성의 머신러닝은 nn.Linear(1,1)의 경우 입력층, 출력층으로 구성하지만, 딥러닝은 nn.Linear(1,1), nn.Linear(1,1)의 경우 입력층, 은닉층 - 은닉층, 출력층으로 구성한다.





In [13]:
# 데이터 정의
import torch

x_train = torch.Tensor([2, 4, 6, 8, 10,
                        12, 14, 16, 18, 20]).view(10,1)
y_train = torch.Tensor([0, 0, 0, 0, 0,
                        0, 1, 1, 1, 1]).view(10,1)

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


In [14]:
# 신경망 모델 구축
from torch import nn

class MyDeepLearningModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8), # 입력층 - 은닉층, 1개의 입력에 대해 8개의 출력을 내놓는 은닉층
            nn.Linear(8, 1), # 은닉층 - 출력층, 8개의 은닉층의 입력에 대해 1개의 출력을 내놓는 출력층
            nn.Sigmoid()
        )

    # 피드 포워드
    def forward(self, data):
        prediction = self.deeplearning_stack(data)
        return prediction

In [15]:
deeplearning_model = MyDeepLearningModel()

# W, b 출력
for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

deeplearning_stack Parameter containing:
tensor([[ 0.1132],
        [ 0.3006],
        [ 0.7448],
        [-0.5364],
        [ 0.7751],
        [ 0.5264],
        [-0.6469],
        [ 0.4914]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-6.2950e-01, -3.6129e-02,  5.0264e-01,  4.2832e-04,  9.7621e-02,
         8.7065e-02, -1.3306e-01,  7.1782e-01], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 0.0056,  0.1494,  0.3486,  0.2633,  0.1525,  0.1346, -0.1921,  0.2614]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([0.1697], requires_grad=True)


입력층 - 은닉층 가중치 1 * 8 = 8개
은닉층 바이어스 8개

은닉층 - 출력층 가중치 8 * 1 = 8개
출력층 바이어스 1개 .. 로 실행 결과를 알 수 있다.

In [18]:
# 손실함수, 옵티마이저

loss_function = nn.BCELoss() # 손실함수, Classification이므로 Binary Cross Entropy 사용

optimizer = torch.optim.SGD(deeplearning_model.parameters(), lr=1e-1) # 옵티마이저, SGD 사용

In [23]:
# 학습

# 5000번 학습
for epoch in range(5001):

  outputs = deeplearning_model(x_train) # 입력값인 x_train에 대한 예측값

  loss = loss_function(outputs, y_train) # 예측값과 정답값 간의 오차

  # 역전파
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  # 100번 째 학습마다 출력
  if epoch % 100 == 0:
      print("Epoch = ", epoch, "Loss = ", loss.item())


Epoch =  0 Loss =  0.0
Epoch =  100 Loss =  0.0
Epoch =  200 Loss =  0.0
Epoch =  300 Loss =  0.0
Epoch =  400 Loss =  0.0
Epoch =  500 Loss =  0.0
Epoch =  600 Loss =  0.0
Epoch =  700 Loss =  0.0
Epoch =  800 Loss =  0.0
Epoch =  900 Loss =  0.0
Epoch =  1000 Loss =  0.0
Epoch =  1100 Loss =  0.0
Epoch =  1200 Loss =  0.0
Epoch =  1300 Loss =  0.0
Epoch =  1400 Loss =  0.0
Epoch =  1500 Loss =  0.0
Epoch =  1600 Loss =  0.0
Epoch =  1700 Loss =  0.0
Epoch =  1800 Loss =  0.0
Epoch =  1900 Loss =  0.0
Epoch =  2000 Loss =  0.0
Epoch =  2100 Loss =  0.0
Epoch =  2200 Loss =  0.0
Epoch =  2300 Loss =  0.0
Epoch =  2400 Loss =  0.0
Epoch =  2500 Loss =  0.0
Epoch =  2600 Loss =  0.0
Epoch =  2700 Loss =  0.0
Epoch =  2800 Loss =  0.0
Epoch =  2900 Loss =  0.0
Epoch =  3000 Loss =  0.0
Epoch =  3100 Loss =  0.0
Epoch =  3200 Loss =  0.0
Epoch =  3300 Loss =  0.0
Epoch =  3400 Loss =  0.0
Epoch =  3500 Loss =  0.0
Epoch =  3600 Loss =  0.0
Epoch =  3700 Loss =  0.0
Epoch =  3800 Loss =  0.

In [25]:
# test
deeplearning_model.eval() # 신경망 모델을 추론 모드로 변환

test_data = torch.Tensor([0.5, 3.0, 3.5, 1.1, 11.0, 15.0, 31.0]).view(7,1)

pred = deeplearning_model(test_data) # 학습 완료 후 , test_data(미지의 데이터)로 예측값 도출

logical_value =  (pred > 0.5).float() # pred > 0.5 True 즉, 1.0 else False 즉, 0.0

print(pred)
print(logical_value)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])


너무 학습해서 그런가..